// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"plugin_center/ent/migrate"

	"plugin_center/ent/ruleinfo"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RuleInfo is the client for interacting with the RuleInfo builders.
	RuleInfo *RuleInfoClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RuleInfo = NewRuleInfoClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		RuleInfo: NewRuleInfoClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		RuleInfo: NewRuleInfoClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RuleInfo.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RuleInfo.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RuleInfo.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RuleInfoMutation:
		return c.RuleInfo.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RuleInfoClient is a client for the RuleInfo schema.
type RuleInfoClient struct {
	config
}

// NewRuleInfoClient returns a client for the RuleInfo from the given config.
func NewRuleInfoClient(c config) *RuleInfoClient {
	return &RuleInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ruleinfo.Hooks(f(g(h())))`.
func (c *RuleInfoClient) Use(hooks ...Hook) {
	c.hooks.RuleInfo = append(c.hooks.RuleInfo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ruleinfo.Intercept(f(g(h())))`.
func (c *RuleInfoClient) Intercept(interceptors ...Interceptor) {
	c.inters.RuleInfo = append(c.inters.RuleInfo, interceptors...)
}

// Create returns a builder for creating a RuleInfo entity.
func (c *RuleInfoClient) Create() *RuleInfoCreate {
	mutation := newRuleInfoMutation(c.config, OpCreate)
	return &RuleInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RuleInfo entities.
func (c *RuleInfoClient) CreateBulk(builders ...*RuleInfoCreate) *RuleInfoCreateBulk {
	return &RuleInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RuleInfo.
func (c *RuleInfoClient) Update() *RuleInfoUpdate {
	mutation := newRuleInfoMutation(c.config, OpUpdate)
	return &RuleInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RuleInfoClient) UpdateOne(ri *RuleInfo) *RuleInfoUpdateOne {
	mutation := newRuleInfoMutation(c.config, OpUpdateOne, withRuleInfo(ri))
	return &RuleInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RuleInfoClient) UpdateOneID(id int) *RuleInfoUpdateOne {
	mutation := newRuleInfoMutation(c.config, OpUpdateOne, withRuleInfoID(id))
	return &RuleInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RuleInfo.
func (c *RuleInfoClient) Delete() *RuleInfoDelete {
	mutation := newRuleInfoMutation(c.config, OpDelete)
	return &RuleInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RuleInfoClient) DeleteOne(ri *RuleInfo) *RuleInfoDeleteOne {
	return c.DeleteOneID(ri.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RuleInfoClient) DeleteOneID(id int) *RuleInfoDeleteOne {
	builder := c.Delete().Where(ruleinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RuleInfoDeleteOne{builder}
}

// Query returns a query builder for RuleInfo.
func (c *RuleInfoClient) Query() *RuleInfoQuery {
	return &RuleInfoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRuleInfo},
		inters: c.Interceptors(),
	}
}

// Get returns a RuleInfo entity by its id.
func (c *RuleInfoClient) Get(ctx context.Context, id int) (*RuleInfo, error) {
	return c.Query().Where(ruleinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RuleInfoClient) GetX(ctx context.Context, id int) *RuleInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RuleInfoClient) Hooks() []Hook {
	return c.hooks.RuleInfo
}

// Interceptors returns the client interceptors.
func (c *RuleInfoClient) Interceptors() []Interceptor {
	return c.inters.RuleInfo
}

func (c *RuleInfoClient) mutate(ctx context.Context, m *RuleInfoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RuleInfoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RuleInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RuleInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RuleInfoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RuleInfo mutation op: %q", m.Op())
	}
}
