// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"plugin_center/ent/predicate"
	"plugin_center/ent/ruleinfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RuleInfoDelete is the builder for deleting a RuleInfo entity.
type RuleInfoDelete struct {
	config
	hooks    []Hook
	mutation *RuleInfoMutation
}

// Where appends a list predicates to the RuleInfoDelete builder.
func (rid *RuleInfoDelete) Where(ps ...predicate.RuleInfo) *RuleInfoDelete {
	rid.mutation.Where(ps...)
	return rid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rid *RuleInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, RuleInfoMutation](ctx, rid.sqlExec, rid.mutation, rid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rid *RuleInfoDelete) ExecX(ctx context.Context) int {
	n, err := rid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rid *RuleInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ruleinfo.Table, sqlgraph.NewFieldSpec(ruleinfo.FieldID, field.TypeInt))
	if ps := rid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rid.mutation.done = true
	return affected, err
}

// RuleInfoDeleteOne is the builder for deleting a single RuleInfo entity.
type RuleInfoDeleteOne struct {
	rid *RuleInfoDelete
}

// Where appends a list predicates to the RuleInfoDelete builder.
func (rido *RuleInfoDeleteOne) Where(ps ...predicate.RuleInfo) *RuleInfoDeleteOne {
	rido.rid.mutation.Where(ps...)
	return rido
}

// Exec executes the deletion query.
func (rido *RuleInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := rido.rid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ruleinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rido *RuleInfoDeleteOne) ExecX(ctx context.Context) {
	if err := rido.Exec(ctx); err != nil {
		panic(err)
	}
}
