// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plugin_center/ent/ruleinfo"
	"plugin_center/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ruleinfoFields := schema.RuleInfo{}.Fields()
	_ = ruleinfoFields
	// ruleinfoDescModule is the schema descriptor for module field.
	ruleinfoDescModule := ruleinfoFields[0].Descriptor()
	// ruleinfo.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	ruleinfo.ModuleValidator = ruleinfoDescModule.Validators[0].(func(string) error)
	// ruleinfoDescPluginType is the schema descriptor for plugin_type field.
	ruleinfoDescPluginType := ruleinfoFields[1].Descriptor()
	// ruleinfo.PluginTypeValidator is a validator for the "plugin_type" field. It is called by the builders before save.
	ruleinfo.PluginTypeValidator = ruleinfoDescPluginType.Validators[0].(func(string) error)
	// ruleinfoDescFilterType is the schema descriptor for filter_type field.
	ruleinfoDescFilterType := ruleinfoFields[2].Descriptor()
	// ruleinfo.FilterTypeValidator is a validator for the "filter_type" field. It is called by the builders before save.
	ruleinfo.FilterTypeValidator = ruleinfoDescFilterType.Validators[0].(func(string) error)
	// ruleinfoDescRuleName is the schema descriptor for rule_name field.
	ruleinfoDescRuleName := ruleinfoFields[3].Descriptor()
	// ruleinfo.RuleNameValidator is a validator for the "rule_name" field. It is called by the builders before save.
	ruleinfo.RuleNameValidator = ruleinfoDescRuleName.Validators[0].(func(string) error)
	// ruleinfoDescRuleBody is the schema descriptor for rule_body field.
	ruleinfoDescRuleBody := ruleinfoFields[4].Descriptor()
	// ruleinfo.RuleBodyValidator is a validator for the "rule_body" field. It is called by the builders before save.
	ruleinfo.RuleBodyValidator = ruleinfoDescRuleBody.Validators[0].(func(string) error)
	// ruleinfoDescCreateTime is the schema descriptor for create_time field.
	ruleinfoDescCreateTime := ruleinfoFields[5].Descriptor()
	// ruleinfo.DefaultCreateTime holds the default value on creation for the create_time field.
	ruleinfo.DefaultCreateTime = ruleinfoDescCreateTime.Default.(time.Time)
	// ruleinfoDescEnable is the schema descriptor for enable field.
	ruleinfoDescEnable := ruleinfoFields[6].Descriptor()
	// ruleinfo.DefaultEnable holds the default value on creation for the enable field.
	ruleinfo.DefaultEnable = ruleinfoDescEnable.Default.(bool)
}
