// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RuleInfosColumns holds the columns for the "rule_infos" table.
	RuleInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "module", Type: field.TypeString},
		{Name: "plugin_type", Type: field.TypeString},
		{Name: "filter_type", Type: field.TypeString},
		{Name: "rule_name", Type: field.TypeString},
		{Name: "rule_body", Type: field.TypeString, Size: 2147483647},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "enable", Type: field.TypeBool, Default: true},
	}
	// RuleInfosTable holds the schema information for the "rule_infos" table.
	RuleInfosTable = &schema.Table{
		Name:       "rule_infos",
		Columns:    RuleInfosColumns,
		PrimaryKey: []*schema.Column{RuleInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RuleInfosTable,
	}
)

func init() {
}
